# install first cmd:-ansible-galaxy collection install community.general 
---
- name: Install a Package and send mail or outlook
  hosts: demo
  remote_user: root
  become: yes
  gather_facts: yes
  tasks:
     - name: Send Email
       community.general.mail:
        host: smtp.gmail.com
        port: 587  # Typically 25 for non-SSL, 465 for SSL/TLS
        username: msaurabh1704@gmail.com
        password: fnjt oheh uzgm sqbf
        to: anikethulule2811@gmail.com
        subject: "Test Email from Ansible"
        body: "This is a test email sent using Ansible."
       delegate_to: localhost
