---
- name: Sending Email
  hosts: 10.127.136.140

  tasks:
   - name: Sending Email
     mail:
       host: smtp.gmail.com
       username: erdigitalmarketer96@gmail.com
       passowrd: hvby oflp uboo nhso
       from: erdigitalmarketer96@gmail.com
       to: ankushkumar5951@gmail.com
       secure: starttls
