---
- name: loops demo play
  hosts: all
  gather_facts: no
  vars:
    fruits:
      - apple
      - orange
      - mango
  tasks:
    - name: Loop over all the softwares
      debug:
        msg: " This is fruit {{ var }} at index {{ index }} "
      loop: "{{ fruits }}"
      loop_control:
        index_var : index
        loop_var : var

