- name: Perform System Patching
  hosts: '{{ hostname | default("localhost") }}'
  become: yes
  tasks:
    - name: Update all packages to the latest version
      yum:
        name: "*"
        state: latest

    - name: Install yum-utils package
      yum:
        name: "yum-utils"
        state: present

    - name: Check if the server needs rebooting
      shell: "needs-restarting -r > /dev/null; echo $?"
      register: needs_restarting

    - name: Display reboot requirement status
      debug:
        msg: '{{ needs_restarting }}'

    - name: Reboot machine if needed
      reboot:
        reboot_timeout: 600
      when: needs_restarting.stdout == "1"
