---
- name: Switches demo play
  hosts: all
  gather_facts: no
  

  tasks:
    - name: Create a user
      user:
        name: Alex
        state: present

      become: true
    - name: Task 2
      debug:
        msg: "This is task 2"

    - name: Task 3
      debug:
        msg: This is task 3"
  
         
